apiVersion: v1
kind: Pod
metadata:
  name: kevin-debug
  namespace: metaflow-jobs
spec:
  containers:
  - name: main
    image: ubuntu:20.04
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    resources:
      requests:
        memory: "8Gi"
        cpu: 1