
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: metaflow-lifecycle
  namespace: metaflow-jobs
spec:
  nats:
    event:
      # url of the nats service
      url: nats://events-nats-cluster
      jsonBody: true
      subject: event
      auth:
        token:
          name: nats-user-token-9l27z
          key: token
      # optional backoff time for connection retries.
      # if not provided, default connection backoff time will be used.
      connectionBackoff:
        # duration in nanoseconds, or strings like "4s", "1m". following value is 10 seconds
        duration: 10s
        # how many backoffs
        steps: 5
        # factor to increase on each step.
        # setting factor > 1 makes backoff exponential.
        factor: 2
        jitter: 0.2