apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: metaflow-webhook
  namespace: metaflow-jobs
spec:
  webhook:
    event:
      port: "12000"
      endpoint: /event
      method: POST
