apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: mf-finished-webhook
  namespace: metaflow-jobs
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    finished:
      port: "12000"
      endpoint: /event
      method: POST